### ISSUE TITLE
2025.6 breaks integration due to async_forward_entry_setup deprication?

### ISSUE THREAD

**Issue by dett80** [dgrassi1984/vitesy-homeassistant#5]
Wass lucky enough to grab API before it was locked out and this integration was working in 2025.5

After upgrading to 2025.6 module fails to load.
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'

hass.config_entries.async_forward_entry_setup was removed in 2025.6
https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

2025-06-12 09:47:23.106 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Vitesy - MW12bGs2aWFtZDpKS3JVVFN1RFpvNGw5ZUw3RmlqU1YxaUpRSGF4Q3JHejIzOWpDUDZk for vitesy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vitesy-homeassistant-main/__init__.py", line 63, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(config_entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

2025-06-12 09:47:31.786 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'vitesy-homeassistant-main' sets option flow config_entry explicitly, which is deprecated at custom_components/vitesy-homeassistant-main/config_flow.py, line 153: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please report it to the author of the 'vitesy-homeassistant-main' custom integration
